# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
test:
  override:    
    - mocha